name: Ruby

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', 'head']
        rubyopt: ['']
        include:
          - ruby: '3.3'
            rubyopt: "--enable-frozen-string-literal --debug-frozen-string-literal"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake RUBYOPT="${{ matrix.rubyopt }}"
